version: '3'
services:
  test_db:
    image: postgres:13
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_vehicle_db  # Nom explicite
    ports:
      - "5433:5432"  # Port différent de la prod (5432)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_vehicle_db"]
